version: '3'
networks:
  bridge1:
    external:
      name: crmpbx_bridge
services:
  php:
    image: yiisoftware/yii2-php:8.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - "$PORT:80"
    environment:
      - DB_ADDRESS=$DB_ADDRESS
      - DB_NAME=$DB_NAME
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - SERVER_ADDRESS=$SERVER_ADDRESS
      - AMO_SERVICE_ADDRESS=$AMO_SERVICE_ADDRESS
      - AMO_TEST_SERVICE_ADDRESS=$AMO_TEST_SERVICE_ADDRESS
      - AMO_SERVICE_TIMEOUT=$AMO_SERVICE_TIMEOUT
      - NOTIFICATION_SERVICE_ADDRESS=$NOTIFICATION_SERVICE_ADDRESS
      - NOTIFICATION_SERVICE_TIMEOUT=$NOTIFICATION_SERVICE_TIMEOUT
      - PIPEDRIVE_SERVICE_ADDRESS=$PIPEDRIVE_SERVICE_ADDRESS
      - PIPEDRIVE_TEST_SERVICE_ADDRESS=$PIPEDRIVE_TEST_SERVICE_ADDRESS
      - PIPEDRIVE_SERVICE_TIMEOUT=$PIPEDRIVE_SERVICE_TIMEOUT
      - EXTENSION_SERVICE_ADDRESS=$EXTENSION_SERVICE_ADDRESS
      - EXTENSION_SERVICE_TIMEOUT=$EXTENSION_SERVICE_TIMEOUT
      - LOG_SERVICE_ADDRESS=$LOG_SERVICE_ADDRESS
      - LOG_SERVICE_TIMEOUT=$LOG_SERVICE_TIMEOUT
      - LOG_SERVICE_ACCESS_TOKEN=$LOG_SERVICE_ACCESS_TOKEN
      - ENV_MODE=$ENV_MODE
      - DEBUG_MODE=$DEBUG_MODE
      - API_AUTH_KEY=$API_AUTH_KEY
    networks:
      bridge1:
        aliases:
          - $SERVICE_NAME_ALIAS