<?php

defined('YII_DEBUG') or define('YII_DEBUG', filter_var($_ENV['DEBUG_MODE'], FILTER_VALIDATE_BOOL));
defined('YII_ENV') or define('YII_ENV', $_ENV['ENV_MODE']);

define('DB_ADDRESS', $_ENV['DB_ADDRESS']);
define('DB_NAME', $_ENV['DB_NAME']);
define('DB_USERNAME', $_ENV['DB_USERNAME']);
define('DB_PASSWORD', $_ENV['DB_PASSWORD']);

define('SERVER_ADDRESS', $_ENV['SERVER_ADDRESS']);

define('NOTIFICATION_SERVICE_TIMEOUT', (int)$_ENV['NOTIFICATION_SERVICE_TIMEOUT']);
define('NOTIFICATION_SERVICE_ADDRESS', $_ENV['NOTIFICATION_SERVICE_ADDRESS']);

define('AMO_SERVICE_TIMEOUT', (int)$_ENV['AMO_SERVICE_TIMEOUT']);
define('AMO_SERVICE_ADDRESS', $_ENV['AMO_SERVICE_ADDRESS']);
define('AMO_TEST_SERVICE_ADDRESS', $_ENV['AMO_TEST_SERVICE_ADDRESS']);

define('PIPEDRIVE_SERVICE_TIMEOUT', (int)$_ENV['PIPEDRIVE_SERVICE_TIMEOUT']);
define('PIPEDRIVE_SERVICE_ADDRESS', $_ENV['PIPEDRIVE_SERVICE_ADDRESS']);
define('PIPEDRIVE_TEST_SERVICE_ADDRESS', $_ENV['PIPEDRIVE_TEST_SERVICE_ADDRESS']);

define('EXTENSION_SERVICE_TIMEOUT', (int)$_ENV['EXTENSION_SERVICE_TIMEOUT']);
define('EXTENSION_SERVICE_ADDRESS', $_ENV['EXTENSION_SERVICE_ADDRESS']);

define('LOG_SERVICE_TIMEOUT', (int)$_ENV['LOG_SERVICE_TIMEOUT']);
define('LOG_SERVICE_ADDRESS', $_ENV['LOG_SERVICE_ADDRESS']);
define('LOG_SERVICE_ACCESS_TOKEN', $_ENV['LOG_SERVICE_ACCESS_TOKEN']);

define('API_AUTH_KEY', $_ENV['API_AUTH_KEY']);
